import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { Inter as FontSans } from 'next/font/google';
import { loadErrorMessages, loadDevMessages } from '@apollo/client/dev';

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
loadDevMessages();
loadErrorMessages();
export default function RootLayout({
  children,
  ...props
}: {
  children: React.ReactNode;
  props: any;
}) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased bg-[#201f1f]',
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
